### ISSUE TITLE
Only one piechart is allowed per page

### ISSUE THREAD

**Issue by kurko** [DmitryBaranovskiy/g.raphael#140]
I'm running into a weird bug: I am not able to have more than one chart per page. If I delete the call to the first pie, than the second shows up, and so on.

Is there a limitation for the number of piecharts we can have in a page?

See this screenshot:

http://cl.ly/2g2T2z1D2G3X3x032r0I

With this code:

```
var data = {
  items: [
    {label: 'One', data: 12015},
    {label: 'Two', data: 23834},
    {label: 'Three', data: 24689}
  ]
};

//Push our data into two separate arrays
var labels = [];
var values = [];
 for (i in data.items) {
   var item = data.items[i];
   labels.push(item.label);
   values.push(item.data);
 }

var r = Raphael("pie_chart");
var pie = r.piechart(60, 60, 50, values, {legend: labels, legendpos: "east"});

var r_two = Raphael("pie_chart_two");
var pie_two = r_two.piechart(60, 60, 50, values, {legend: labels, legendpos: "east"});

var r_three = Raphael("pie_chart_three");
var pie_three = r_three.piechart(60, 60, 50, values, {legend: labels, legendpos: "east"});
```

**Comment by picofaradpjf** [comment]
I had the same problem.  But if you use a different array variable for the values for each chart it will work.  Oddly even though sharing the same values array doesn't work, the charts can use the same labels array.

**Comment by kurko** [comment]
Thanks. I'll test this tomorrow.

**Comment by karolk** [comment]
Definitely you can have many instances of piechart per page. The problem here is g.raphael is modifying the array with data for no apparent reason, so it cannot be reused. At the moment I am planning to modify this behaviour to keep the values array intact, since I don't know of any benefits of this currently existing.

Example of 2 charts in the same svg object: http://jsbin.com/ehoxur/1
