### ISSUE TITLE
Is there a way to set a max value for an axis?

### ISSUE THREAD

**Issue by ryanbooker** [DmitryBaranovskiy/g.raphael#37]
e.g. I want my Y axis to have a max of 100, and scale the actual y values accordingly. i.e. so that the chart always has the same proprtions, rather than the proportions being relative to the min and max value supplied.

**Comment by ryanbooker** [comment]
e.g.
http://github.com/ryanbooker/g.raphael/commit/c40a6d7d64bfb89ccc41c885937be55d6c6eff4c

UPDATE: I've updated the link to a better commit. 0 values wouldn't work with the previous one.

**Comment by eendeego** [comment]
Hi,

My two commits below also fix this and also clip the chart so that it doesn't overflow if the chart ranges (minimum and maximum x/y) are smaller than the values on the chart data. 

(I'm sorry, I've made the first commit before checking this bug).

http://github.com/luismreis/g.raphael/commit/16987398f8a13662230c1b9a75fdfa5ff233c843
http://github.com/luismreis/g.raphael/commit/2d4540cefee685de3f9d46dc5478d8e4ae9f5ae9

These commits also fix issue #8.
